// Generated by Wrangler by running `wrangler types`

interface Env {
        ASSETS: Fetcher;
        OPENAI_API_KEY: string;
        GITHUB_TOKEN: string;
        GITHUB_REPO: string;
        SLACK_WEBHOOK_URL: string;
        pseudointelekt_contact_form: KVNamespace;
        pseudointelekt_views: KVNamespace;
        pseudointelekt_likes: KVNamespace;
}
