// Generated by Wrangler by running `wrangler types`

interface Env {
        ASSETS: Fetcher;
        OPENAI_API_KEY: string;
        GITHUB_TOKEN: string;
        GITHUB_REPO: string;
        SLACK_WEBHOOK_URL: string;
        pseudointelekt_contact_form: KVNamespace;
        pseudointelekt_views: KVNamespace;
        pseudointelekt_likes: KVNamespace;
        WORKER_ID: string;
        OPENAI_TEXT_MODEL: string;
        OPENAI_TOPIC_MODEL?: string;
        OPENAI_OUTLINE_MODEL?: string;
        OPENAI_DRAFT_MODEL?: string;
        OPENAI_EDIT_MODEL?: string;
        OPENAI_REPAIR_MODEL?: string;
        OPENAI_IMAGE_MODEL?: string;
        OPENAI_IMAGE_SIZE?: string;
        OPENAI_IMAGE_STYLE: string;
        OPENAI_IMAGE_QUALITY: string;
        TEXT_GENERATION_PROVIDER?: string;
        TEXT_GENERATION_FALLBACK?: string;
        TEXT_GENERATION_FALLBACK_MODEL?: string;
        TEXT_TOPIC_SELECTION?: string;
        TEXT_ARTICLE_PIPELINE?: string;
        TEXT_SECTION_PARAGRAPHS?: string;
        TEXT_SECTION_MAX_TOKENS?: string;
        JETSON_GATEWAY_URL?: string;
        JETSON_GATEWAY_TOKEN?: string;
        JETSON_GATEWAY_MODEL?: string;
        JETSON_GATEWAY_TIMEOUT_MS?: string;
        JETSON_GATEWAY_DISABLE_THINKING?: string;
        JETSON_ACCESS_CLIENT_ID?: string;
        JETSON_ACCESS_CLIENT_SECRET?: string;
        CF_ACCESS_TEAM_DOMAIN?: string;
        CF_ACCESS_AUD?: string;
        CF_ACCESS_ALLOWED_EMAILS?: string;
        pseudointelekt_logs_db: D1Database;
}
